FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o server ./src/main.go


FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata

RUN mkdir -p /app/src/logs

COPY --from=builder /app/server .
COPY --from=builder /app/migrations ./migrations
COPY .env ./
EXPOSE 8080

CMD ["./server"]
